src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\ReportYourBug\Report;
use App\Repository\UserRepository;
use App\Tools\Roles;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Boolean;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"username"}, message="Il existe déjà un compte avec ce nom d'utilisateur")
 * @UniqueEntity(fields={"email"}, message="Il existe déjà un compte avec cette adresse mail")
 * @ORM\Table(name="idevlab_user")
 */
class User implements UserInterface
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="array")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=30,nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=40,nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity=Report::class, mappedBy="author")
     */
    private $reports;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $avatar = "default.jpg";

    public function __construct()
    {
        $this->reports = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function getRole(): String
    {
        $role = 'Utilisateur';
        if (in_array(Roles::SUPER_ADMIN,$this->roles)) {
            $role = 'Super Administrateur';
        } else if (in_array(Roles::ADMIN,$this->roles)) {
            $role = 'Administrateur';
        }

        return $role;
    }

    public function isSuperAdmin(): bool
    {
        return in_array(Roles::SUPER_ADMIN,$this->roles);
    }

    public function isAdmin(): bool
    {
        if ($this->isSuperAdmin()) return true;
        return in_array(Roles::ADMIN,$this->roles);
    }


    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFullName(): ?string
    {
        return $this->firstName . " " . $this->lastName;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|Report[]
     */
    public function getReports(): Collection
    {
        return $this->reports;
    }

    public function addReport(Report $report): self
    {
        if (!$this->reports->contains($report)) {
            $this->reports[] = $report;
            $report->setAuthor($this);
        }

        return $this;
    }

    public function removeReport(Report $report): self
    {
        if ($this->reports->removeElement($report)) {
            // set the owning side to null (unless already changed)
            if ($report->getAuthor() === $this) {
                $report->setAuthor(null);
            }
        }

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }
}

templates/layouts/dashboard/footer-bottom-scripts.html.twig
{% if not app.user.superAdmin %}
<script>
    $(document).ready(function(){
        $("#edit_profile_form_roles_0,#edit_profile_form_roles_1,#add_profile_form_roles_0,#add_profile_form_roles_1").attr("disabled", true);
    })
</script>
    <script src="{{ asset("assets/add-on/Table/vendor/select2/select2.min.js") }}"></script>
{% endif %}

templates/layouts/dashboard/footer.html.twig
    <!-- Warning Section start -->
    <!-- Older IE warning message -->
    <!--[if lt IE 11]>
        <div class="ie-warning">
            <h1>Attention!!</h1>
            <p>Vous utilisez une version obsolète d'Internet Explorer, veuillez mettre à niveau
                <br/>à l'un des navigateurs Web suivants pour accéder à ce site Web.
            </p>
            <div class="iew-container">
                <ul class="iew-download">
                    <li>
                        <a href="http://www.google.com/chrome/">
                            <img src="{{ asset('assets/images/browser/chrome.png') }}" alt="Chrome">
                            <div>Chrome</div>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.mozilla.org/en-US/firefox/new/">
                            <img src="{{ asset('assets/images/browser/firefox.png') }}" alt="Firefox">
                            <div>Firefox</div>
                        </a>
                    </li>
                    <li>
                        <a href="http://www.opera.com">
                            <img src="{{ asset('assets/images/browser/opera.png') }}" alt="Opera">
                            <div>Opera</div>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.apple.com/safari/">
                            <img src="{{ asset('assets/images/browser/safari.png') }}" alt="Safari">
                            <div>Safari</div>
                        </a>
                    </li>
                    <li>
                        <a href="http://windows.microsoft.com/en-us/internet-explorer/download-ie">
                            <img src="{{ asset('assets/images/browser/ie.png') }}" alt="">
                            <div>IE (11 & above)</div>
                        </a>
                    </li>
                </ul>
            </div>
            <p>Désolé pour le dérangement!</p>
        </div>
    <![endif]-->
    <!-- Warning Section Ends -->
    <!-- Required Js -->
    <script src="{{ asset('assets/js/vendor-all.min.js') }}"></script>
    <script src="{{ asset('assets/js/plugins/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/js/plugins/feather.min.js') }}"></script>
    <script src="{{ asset('assets/js/pcoded.min.js') }}"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script> -->
    <!-- <script src="assets/js/plugins/clipboard.min.js"></script> -->
    <!-- <script src="assets/js/uikit.min.js"></script> -->

templates/layouts/dashboard/head-bottom-link.html.html.twig
<!-- font css -->
<link rel="stylesheet" href="{{ asset('assets/fonts/feather.css') }}">
<link rel="stylesheet" href="{{ asset('assets/fonts/fontawesome.css') }}">
<link rel="stylesheet" href="{{ asset('assets/fonts/font-awesome/css/all.css') }}">
<link rel="stylesheet" href="{{ asset('assets/fonts/material.css') }}">

<link rel="stylesheet" href="{{ asset('assets/css/flow.css') }}" id="main-style-link">

<!-- vendor css -->
<link rel="stylesheet" href="{{ asset('assets/css/style.css') }}" id="main-style-link">

<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

templates/layouts/dashboard/head.html.twig
<!-- HTML5 Shim and Respond.js IE11 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 11]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->
<!-- Meta -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="author" content="IDevLab ">


<!-- Favicon icon -->
<link rel="icon" href="{{ asset('favicon.ico') }}" type="image/x-icon">
<!-- Material Icon -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

templates/layouts/dashboard/header-content.html.twig
{# <div class="mr-auto pc-mob-drp">
	<ul class="list-unstyled">
		<li class="dropdown pc-h-item">
			<a class="pc-head-link active dropdown-toggle arrow-none mr-0" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
				{{ app.user.username }}
			</a>
			<div class="dropdown-menu pc-h-dropdown">
				<a href="#!" class="dropdown-item">
					<i class="material-icons-two-tone">account_circle</i>
					<span>Mon compte</span>
				</a>
				Sub-Dropdown
				<div class="pc-level-menu">
					<a href="#!" class="dropdown-item">
						<i class="material-icons-two-tone">list_alt</i>
						<span class="float-right"><i data-feather="chevron-right" class="mr-0"></i></span>
						<span>{{ app.user.username }}</span>
					</a>
					<div class="dropdown-menu pc-h-dropdown">
						<a href="#!" class="dropdown-item">
							<i class="fas fa-circle"></i>
							<span>Mon compte</span>
						</a>
						<a href="#!" class="dropdown-item">
							<i class="fas fa-circle"></i>
							<span>Paramètres</span>
						</a>
						<a href="{{ path('app_logout') }}" class="dropdown-item">
							<i class="fas fa-circle"></i>
							<span>Déconnexion</span>
						</a>
					</div>
				</div>
				<a href="#" class="dropdown-item">
					<i class="material-icons-two-tone">settings</i>
					<span>Paramètres</span>
				</a>
				<a href="{{ path('app_logout') }}" class="dropdown-item">
					<i class="material-icons-two-tone">chrome_reader_mode</i>
					<span>Déconnexion</span>
				</a>
			</div>
		</li>
	</ul>
</div> #}
<div class="ml-auto">
	<ul class="list-unstyled">
		<li class="dropdown pc-h-item">
			<a class="pc-head-link dropdown-toggle arrow-none mr-0" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
				<i class="material-icons-two-tone">search</i>
			</a>
			<div class="dropdown-menu dropdown-menu-right pc-h-dropdown drp-search">
				<form class="px-3">
					<div class="form-group mb-0 d-flex align-items-center">
						<i data-feather="search"></i>
						<input type="search" class="form-control border-0 shadow-none" placeholder="Rechercher ici. . .">
					</div>
				</form>
			</div>
		</li>
		<li class="dropdown pc-h-item">
			<a class="pc-head-link dropdown-toggle arrow-none mr-0" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
				<img src="{{ asset(avatar_path~app.user.avatar) }}" alt="user-image" class="user-avtar">
				<span>
					<span class="user-name">{{ app.user.fullName }}</span>
					<span class="user-desc">{{ app.user.role }}</span>
				</span>
			</a>
			<div class="dropdown-menu dropdown-menu-right pc-h-dropdown">
				<a href="{{ path('admin_user_details', {'id': app.user.id}) }}" class="dropdown-item">
					<i class="fas fa-user-circle"></i>
					<span>Mon compte</span>
				</a>
				{#  Sub-Dropdown
				<div class="pc-level-menu">
					<a href="#!" class="dropdown-item">
						<i class="material-icons-two-tone">list_alt</i>
						<span class="float-right"><i data-feather="chevron-right" class="mr-0"></i></span>
						<span>{{ app.user.username }}</span>
					</a>
					<div class="dropdown-menu pc-h-dropdown">
						<a href="#!" class="dropdown-item">
							<i class="fas fa-circle"></i>
							<span>Mon compte</span>
						</a>
						<a href="#!" class="dropdown-item">
							<i class="fas fa-circle"></i>
							<span>Paramètres</span>
						</a>
						<a href="{{ path('app_logout') }}" class="dropdown-item">
							<i class="fas fa-circle"></i>
							<span>Déconnexion</span>
						</a>
					</div>
				</div>
				#}
				<a href="#" class="dropdown-item">
					<i class="fas fa-cog"></i>
					<span>Paramètres</span>
				</a>
				<a href="{{ path('app_logout') }}" class="dropdown-item">
					<i class="fas fa-sign-out-alt"></i>
					<span>Déconnexion</span>
				</a>
			</div>
		</li>
	</ul>
</div>

templates/layouts/dashboard/layout-vertical.html.twig
	<!-- [ Pre-loader ] start -->
	<div class="loader-bg">
		<div class="loader-track">
			<div class="loader-fill"></div>
		</div>
	</div>
	<!-- [ Pre-loader ] End -->
	<!-- [ Mobile header ] start -->
	<div class="pc-mob-header pc-header">
		<div class="pcm-logo">
			<img src="{{ asset('assets/images/logo/logo compact.svg') }}" alt="" class="logo logo-lg">
		</div>
		<div class="pcm-toolbar">
			<a href="#!" class="pc-head-link" id="mobile-collapse">
				<div class="hamburger hamburger--arrowturn">
					<div class="hamburger-box">
						<div class="hamburger-inner"></div>
					</div>
				</div>
			</a>
			<a href="#!" class="pc-head-link" id="headerdrp-collapse">
				<i data-feather="align-right"></i>
			</a>
			<a href="#!" class="pc-head-link" id="header-collapse">
				<i data-feather="more-vertical"></i>
			</a>
		</div>
	</div>
	<!-- [ Mobile header ] End -->

	<!-- [ navigation menu ] start -->
	<nav class="pc-sidebar @@menuclass">
		<div class="navbar-wrapper">
			<div class="m-header">
				<a href="{{ path('admin_home') }}" class="b-brand">
					<!-- ========   change your logo hear   ============ -->
					<img src="{{ asset('assets/images/logo/logo.png') }}" alt="" class="logo logo-lg"  style="width: 100%">
					<img src="{{ asset('assets/images/logo/logo compact min.png') }}" alt="" class="logo logo-sm"  style="width: 100%">
				</a>
			</div>
			<div class="navbar-content">
				<ul class="pc-navbar">
					{{ include('layouts/dashboard/menu-list.html.twig')}}
				</ul>
			</div>
		</div>
	</nav>
	<!-- [ navigation menu ] end -->
	<!-- [ Header ] start -->
	<header class="pc-header @@headerclass">
		<div class="header-wrapper">
			{{ include('layouts/dashboard/header-content.html.twig') }}
		</div>
	</header>
	<!-- [ Header ] end -->

templates/layouts/dashboard/menu-list.html.twig
<li class="pc-item pc-caption">
	<label>Navigation</label>
</li>
<li>
	<a href="{{ path('admin_home') }}" class="pc-link "><span class="pc-micon"><i class="material-icons-two-tone">home</i></span><span class="pc-mtext">Tableau de bord</span></a>
</li>
<li class="pc-item pc-caption">
	<label>{{ app_name }}</label>
	<span>Gestion</span>
</li>
<li class="pc-item pc-hasmenu">
	<a class="pc-link "><span class="pc-micon"><i class="fas fa-user"></i></span><span class="pc-mtext">Utilisateurs</span><span class="pc-arrow"><i data-feather="chevron-right"></i></span></a>
	<ul class="pc-submenu">
		<li><a class="pc-link" href="{{ path('admin_users', {'role': 'Tous'}) }}"><i class="fas fa-users"></i> Tous</a></li>
		<li><a class="pc-link" href="{{ path('admin_users', {'role': 'Utilisateur'}) }}"><i class="fas fa-user-friends"></i> Utilisateurs</a></li>
		<li><a class="pc-link" href="{{ path('admin_users', {'role': 'Administrateur'}) }}"><i class="fas fa-user-lock"></i> Administrateurs</a></li>
		<li><a class="pc-link" href="{{ path('admin_users', {'role': 'SuperAdministrateur'}) }}"><i class="fas fa-user-shield"></i> Super Administrateurs</a></li>
	</ul>
</li>
<li class="pc-item pc-caption">
	<label>Portfolio</label>
</li>
<li class="pc-item pc-hasmenu">
	<a class="pc-link "><span class="pc-micon"><i class="fas fa-archive"></i></span><span class="pc-mtext">Projets</span><span class="pc-arrow"><i data-feather="chevron-right"></i></span></a>
	<ul class="pc-submenu">
		<li><a class="pc-link" href="{{ path('admin_portfolio_liste') }}"><i class="fas fa-list"></i> Liste</a></li>
		<li><a class="pc-link" href="#"><i class="fas fa-plus"></i> Ajouter</a></li>
		<li><a class="pc-link" href="#"><i class="fas fa-edit"></i> Modifier</a></li>
	</ul>
</li>
<li class="pc-item pc-hasmenu">
	<a class="pc-link "><span class="pc-micon"><i class="fas fa-th-list"></i></span><span class="pc-mtext">Catégories</span><span class="pc-arrow"><i data-feather="chevron-right"></i></span></a>
	<ul class="pc-submenu">
		<a class="pc-link" href="#"><i class="fas fa-list"></i> Liste</a>
		<li><a class="pc-link" href="#"><i class="fas fa-plus"></i> Ajouter</a></li>
		<li><a class="pc-link" href="#"><i class="fas fa-edit"></i> Modifier</a></li>
	</ul>
</li>
<li class="pc-item pc-hasmenu">
	<a class="pc-link "><span class="pc-micon"><i class="fas fa-th-list"></i></span><span class="pc-mtext">Compétences</span><span class="pc-arrow"><i data-feather="chevron-right"></i></span></a>
	<ul class="pc-submenu">
		<a class="pc-link" href="#"><i class="fas fa-list"></i> Liste</a>
		<li><a class="pc-link" href="#"><i class="fas fa-plus"></i> Ajouter</a></li>
		<li><a class="pc-link" href="#"><i class="fas fa-edit"></i> Modifier</a></li>
	</ul>
</li>
<li class="pc-item pc-caption">
	<label>Report Your Bugs</label>
	<span>Gestion</span>
</li>
<li class="pc-item pc-hasmenu">
	<a class="pc-link "><span class="pc-micon"><i class="fas fa-archive"></i></span><span class="pc-mtext">Rapports</span><span class="pc-arrow"><i data-feather="chevron-right"></i></span></a>
	<ul class="pc-submenu">
		<a class="pc-link" href="#"><i class="fas fa-list"></i> Liste</a>
		<li><a class="pc-link" href="#"><i class="fas fa-plus"></i> Ajouter</a></li>
		<li><a class="pc-link" href="#"><i class="fas fa-edit"></i> Modifier</a></li>
	</ul>
</li>
<li class="pc-item pc-hasmenu">
	<a class="pc-link "><span class="pc-micon"><i class="fas fa-th-list"></i></span><span class="pc-mtext">Technologies</span><span class="pc-arrow"><i data-feather="chevron-right"></i></span></a>
	<ul class="pc-submenu">
		<a class="pc-link" href="#"><i class="fas fa-list"></i> Liste</a>
		<li><a class="pc-link" href="#"><i class="fas fa-plus"></i> Ajouter</a></li>
		<li><a class="pc-link" href="#"><i class="fas fa-edit"></i> Modifier</a></li>
	</ul>
</li>
<li class="pc-item pc-hasmenu">
	<a class="pc-link "><span class="pc-micon"><i class="fas fa-th-list"></i></span><span class="pc-mtext">Catégories</span><span class="pc-arrow"><i data-feather="chevron-right"></i></span></a>
	<ul class="pc-submenu">
		<a class="pc-link" href="#"><i class="fas fa-list"></i> Liste</a>
		<li><a class="pc-link" href="#"><i class="fas fa-plus"></i> Ajouter</a></li>
		<li><a class="pc-link" href="#"><i class="fas fa-edit"></i> Modifier</a></li>
	</ul>
</li>
{# Others Cat
	<li class="pc-item pc-caption">
	<label>Report Your Bugs</label>
	<span>Gestion</span>
</li>
<li class="pc-item pc-caption">
	<label>Chart & Maps</label>
	<span>Tones of readymade charts</span>
</li>
<li>
	<a href="chart-apex.html" class="pc-link "><span class="pc-micon"><i class="material-icons-two-tone">bubble_chart</i></span><span class="pc-mtext">Chart</span></a>
</li>
<li>
	<a href="map-google.html" class="pc-link "><span class="pc-micon"><i class="material-icons-two-tone">my_location</i></span><span class="pc-mtext">Maps</span></a>
</li>
<li class="pc-item pc-caption">
	<label>Pages</label>
	<span>Redymade Pages</span>
</li>
<li class="pc-item pc-hasmenu">
	<a href="#!" class="pc-link"><span class="pc-micon"><i class="material-icons-two-tone">https</i></span><span class="pc-mtext">Authentication</span><span class="pc-arrow"><i data-feather="chevron-right"></i></span></a>
	<ul class="pc-submenu">
		<li><a class="pc-link" href="auth-signup.html" target="_blank">Sign up</a></li>
		<li><a class="pc-link" href="auth-signin.html" target="_blank">Sign in</a></li>
	</ul>
</li>
<li class="pc-item pc-caption">
	<label>Other</label>
	<span>Extra more things</span>
</li>
<li class="pc-item pc-hasmenu">
	<a href="#!" class="pc-link"><span class="pc-micon"><i class="material-icons-two-tone">list_alt</i></span><span class="pc-mtext">Menu levels</span><span class="pc-arrow"><i data-feather="chevron-right"></i></span></a>
	<ul class="pc-submenu">
		<li><a class="pc-link" href="#!">Menu Level 2.1</a></li>
		<li class="pc-item pc-hasmenu">
			<a href="#!" class="pc-link">Menu level 2.2<span class="pc-arrow"><i data-feather="chevron-right"></i></span></a>
			<ul class="pc-submenu">
				<li><a class="pc-link" href="#!">Menu level 3.1</a></li>
				<li><a class="pc-link" href="#!">Menu level 3.2</a></li>
				<li class="pc-item pc-hasmenu">
					<a href="#!" class="pc-link">Menu level 3.3<span class="pc-arrow"><i data-feather="chevron-right"></i></span></a>
					<ul class="pc-submenu">
						<li><a class="pc-link" href="#!">Menu level 4.1</a></li>
						<li><a class="pc-link" href="#!">Menu level 4.2</a></li>
					</ul>
				</li>
			</ul>
		</li>
		<li class="pc-item pc-hasmenu">
			<a href="#!" class="pc-link">Menu level 2.3<span class="pc-arrow"><i data-feather="chevron-right"></i></span></a>
			<ul class="pc-submenu">
				<li><a class="pc-link" href="#!">Menu level 3.1</a></li>
				<li><a class="pc-link" href="#!">Menu level 3.2</a></li>
				<li class="pc-item pc-hasmenu">
					<a href="#!" class="pc-link">Menu level 3.3<span class="pc-arrow"><i data-feather="chevron-right"></i></span></a>
					<ul class="pc-submenu">
						<li><a class="pc-link" href="#!">Menu level 4.1</a></li>
						<li><a class="pc-link" href="#!">Menu level 4.2</a></li>
					</ul>
				</li>
			</ul>
		</li>
	</ul>
</li>
<li><a href="sample-page.html" class="pc-link "><span class="pc-micon"><i class="material-icons-two-tone">storefront</i></span><span class="pc-mtext">Sample page</span></a></li>

#}