src/Entity/Portfolio/Project.php
<?php

namespace App\Entity\Portfolio;

use App\Repository\Portfolio\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 * @ORM\Table(name="portfolio_projects")
 */
class Project
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $version;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $githubRepository;

    /**
     * @ORM\Column(type="text", length=500)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $client_name = "Pas de client pour se projet";

    /**
     * @ORM\Column(type="datetime")
     */
    private $start_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $end_date;

    /**
     * @ORM\ManyToOne(targetEntity=State::class, inversedBy="projects")
     * @ORM\JoinColumn(nullable=false)
     */
    private $State;

    /**
     * @ORM\ManyToMany(targetEntity=Skill::class, inversedBy="projects")
     * @ORM\JoinTable(name="portfolio_project_skill")
     */
    private $Skills;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture = "default.jpg";

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $secondary_picture = "default.jpg";

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="projects")
     * @ORM\JoinTable(name="portfolio_project_category")
     */
    private $categories;

    /**
     * @ORM\ManyToMany(targetEntity=Feature::class, inversedBy="projects")
     * @ORM\JoinTable(name="portfolio_project_feature")
     * @ORM\JoinTable
     */
    private $features;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isPublished;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $projectLink;

    public function __construct()
    {
        $this->Skills = new ArrayCollection();
        $this->categories = new ArrayCollection();
        $this->features = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getVersion(): ?string
    {
        return $this->version;
    }

    public function setVersion(string $version): self
    {
        $this->version = $version;

        return $this;
    }

    public function getGithubRepository(): ?string
    {
        return $this->githubRepository;
    }

    public function setGithubRepository(?string $githubRepository): self
    {
        $this->githubRepository = $githubRepository;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getClientName(): ?string
    {
        return $this->client_name;
    }

    public function setClientName(?string $client_name): self
    {
        $this->client_name = $client_name;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(?\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getState(): ?State
    {
        return $this->State;
    }

    public function setState(?State $State): self
    {
        $this->State = $State;

        return $this;
    }

    /**
     * @return Collection|Skill[]
     */
    public function getSkills(): Collection
    {
        return $this->Skills;
    }

    public function addSkill(Skill $skill): self
    {
        if (!$this->Skills->contains($skill)) {
            $this->Skills[] = $skill;
        }

        return $this;
    }

    public function removeSkill(Skill $skill): self
    {
        $this->Skills->removeElement($skill);

        return $this;
    }

    public function showSkills() {

        $string = null;
        $separator = " / ";

        foreach ($this->Skills as $skill) {
            $string .= $skill->getTitle();
            $string .= $separator;
        }

        return rtrim($string, $separator);
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getSecondaryPicture(): ?string
    {
        return $this->secondary_picture;
    }

    public function setSecondaryPicture(?string $secondary_picture): self
    {
        $this->secondary_picture = $secondary_picture;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->categories->removeElement($category);

        return $this;
    }

    public function showCategories() {
        $string = null;
        $separator = " / ";

        foreach ($this->categories as $category) {
            $string .= $category->getTitle();
            $string .= $separator;
        }

        return rtrim($string, $separator);
    }

    /**
     * @return Collection|Feature[]
     */
    public function getFeatures(): Collection
    {
        return $this->features;
    }

    public function addFeature(Feature $feature): self
    {
        if (!$this->features->contains($feature)) {
            $this->features[] = $feature;
        }

        return $this;
    }

    public function removeFeature(Feature $feature): self
    {
        $this->features->removeElement($feature);

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setIsPublished(bool $isPublished): self
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    public function getProjectLink(): ?string
    {
        return $this->projectLink;
    }

    public function setProjectLink(?string $projectLink): self
    {
        $this->projectLink = $projectLink;

        return $this;
    }
}

src/Entity/ReportYourBug/Report.php
<?php

namespace App\Entity\ReportYourBug;

use App\Entity\User;
use App\Repository\ReportYourBug\ReportRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReportRepository::class)
 * @ORM\Table(name="ryb_report")
 */
class Report
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", length=500)
     */
    private $cause;

    /**
     * @ORM\Column(type="text", length=500, nullable=true)
     */
    private $solution;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isResolved;

    /**
     * @ORM\Column(type="datetime")
     */
    private $open_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $claused_at;

    /**
     * @ORM\ManyToOne(targetEntity=Technology::class, inversedBy="reports")
     */
    private $technology;

    /**
     * @ORM\ManyToMany(targetEntity=Type::class, inversedBy="reports")
     * @ORM\JoinTable(name="ryb_report_type")
     */
    private $types;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reports")
     * @ORM\JoinColumn(nullable=true)
     */
    private $author;

    public function __construct()
    {
        $this->types = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCause(): ?string
    {
        return $this->cause;
    }

    public function setCause(string $cause): self
    {
        $this->cause = $cause;

        return $this;
    }

    public function getSolution(): ?string
    {
        return $this->solution;
    }

    public function setSolution(?string $solution): self
    {
        $this->solution = $solution;

        return $this;
    }

    public function getIsResolved(): ?bool
    {
        return $this->isResolved;
    }

    public function setIsResolved(bool $isResolved): self
    {
        $this->isResolved = $isResolved;

        return $this;
    }

    public function getOpenAt(): ?\DateTimeInterface
    {
        return $this->open_at;
    }

    public function setOpenAt(\DateTimeInterface $open_at): self
    {
        $this->open_at = $open_at;

        return $this;
    }

    public function getClausedAt(): ?\DateTimeInterface
    {
        return $this->claused_at;
    }

    public function setClausedAt(?\DateTimeInterface $claused_at): self
    {
        $this->claused_at = $claused_at;

        return $this;
    }

    public function getTechnology(): ?Technology
    {
        return $this->technology;
    }

    public function setTechnology(?Technology $technology): self
    {
        $this->technology = $technology;

        return $this;
    }

    /**
     * @return Collection|Type[]
     */
    public function getTypes(): Collection
    {
        return $this->types;
    }

    public function addType(Type $type): self
    {
        if (!$this->types->contains($type)) {
            $this->types[] = $type;
        }

        return $this;
    }

    public function removeType(Type $type): self
    {
        $this->types->removeElement($type);

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }
}

src/Entity/ReportYourBug/Technology.php
<?php

namespace App\Entity\ReportYourBug;

use App\Repository\ReportYourBug\TechnologyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TechnologyRepository::class)
 * @ORM\Table(name="ryb_technology")
 */
class Technology
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity=Report::class, mappedBy="technology")
     */
    private $reports;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_path;

    public function __construct()
    {
        $this->reports = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Report[]
     */
    public function getReports(): Collection
    {
        return $this->reports;
    }

    public function addReport(Report $report): self
    {
        if (!$this->reports->contains($report)) {
            $this->reports[] = $report;
            $report->setTechnology($this);
        }

        return $this;
    }

    public function removeReport(Report $report): self
    {
        if ($this->reports->removeElement($report)) {
            // set the owning side to null (unless already changed)
            if ($report->getTechnology() === $this) {
                $report->setTechnology(null);
            }
        }

        return $this;
    }

    public function getImagePath(): ?string
    {
        return $this->image_path;
    }

    public function setImagePath(?string $image_path): self
    {
        $this->image_path = $image_path;

        return $this;
    }
}

src/Entity/ReportYourBug/Type.php
<?php

namespace App\Entity\ReportYourBug;

use App\Repository\ReportYourBug\TypeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TypeRepository::class)
 * @ORM\Table(name="ryb_type")
 */
class Type
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToMany(targetEntity=Report::class, mappedBy="types")
     */
    private $reports;

    public function __construct()
    {
        $this->reports = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Report[]
     */
    public function getReports(): Collection
    {
        return $this->reports;
    }

    public function addReport(Report $report): self
    {
        if (!$this->reports->contains($report)) {
            $this->reports[] = $report;
            $report->addType($this);
        }

        return $this;
    }

    public function removeReport(Report $report): self
    {
        if ($this->reports->removeElement($report)) {
            $report->removeType($this);
        }

        return $this;
    }
}

src/Controller/API/ReportYourBug/ApiController.php
<?php

namespace App\Controller\API\ReportYourBug;

use App\Repository\ReportYourBug\ReportRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/api/reportYourBug')]
class ApiController extends AbstractController
{

    /**
     * @param ReportRepository $repository
     * @param Request $request
     * @return Response
     */
    #[Route("/reports/render", name:"api_ryb_list_render_render")]
    public function apiListReportByTitle(ReportRepository $repository,Request $request): Response
    {
        $reports = $repository->findByFilter(
            (String) $request->get("title")??null,
            (int) $request->get("id")??null,
            (int) $request->get("technology")??null,
            (array) $request->get("types")??null
        );


        return $this->render('reportYourBug/ApiTemplates/listTemplate.html.twig', [
            "reportList" => $reports
        ]);
    }
}

src/Controller/ReportYourBug/AppController.php
<?php

namespace App\Controller\ReportYourBug;

use App\Repository\ReportYourBug\ReportRepository;
use App\Repository\ReportYourBug\TechnologyRepository;
use App\Repository\ReportYourBug\TypeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route("/ReportYourBug")]
class AppController extends AbstractController
{
    /**
     * @param ReportRepository $reportRepository
     * @param TechnologyRepository $technologyRepository
     * @param TypeRepository $typeRepository
     * @return Response
     */
    #[Route("/accueil", name:"ryb_home")]
    public function homePage(ReportRepository $reportRepository,TechnologyRepository $technologyRepository,TypeRepository $typeRepository): Response
    {
        $reports = $reportRepository->findAll();
        $technologies = $technologyRepository->findAll();
        $types = $typeRepository->findAll();


        return $this->render('reportYourBug/index.html.twig', [
            "reportList" => $reports,
            "typesList" => $types,
            "technologyList" => $technologies
        ]);
    }
}

templates/ReportYourBug/index.html.twig
{% extends "layouts/triangle/base.html.twig" %}

{% block title %} RYB | Accueil {% endblock %}

{% block head %}
    <link rel="icon" type="image/x-icon" href="{{ asset('assets/images/ico/ReportYourBug/Logo.png') }}" />
{% endblock %}

{% block Home_Slider %}
    <section id="page-breadcrumb" class="f-banner">
        <div class="vertical-center sun">
            <div class="container">
                <div class="row">
                    <div class="action">
                        <div class="col-sm-12">
                            <h1 class="title">Report your bugs</h1>
                            <p>Garder une trace de vos erreur pour les résoudres plus vite.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{%  block Content %}
<div class="f-container" id="modal-closed">

    <div class="f-filter-container">
        <div class="f-filter-row">
            <input type="number" class="f-filter-id form-control" id="recherche-par-id" placeholder="ID" min="0">
            <input type="search" class="f-search-bar form-control" id="recherche-par-titre" placeholder="Recherche" >
        </div>
        <div class="f-filter-row">
            <select id="recherche-par-technology" class="f-filter-technology form-control">
                <option value=null>-- Tchnologie --</option>
                {% for technology in technologyList %}
                    <option value={{ technology.id }}>{{ technology.name }}</option>
                {% endfor %}
            </select>

            <select id="recherche-par-type" class="f-filter-type form-control" multiple="multiple">
                {% for type in typesList %}
                    <option value={{ type.id }}>{{ type.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <div class="wrap-table100">
            <div class="table100 ver1 m-b-110">
                <div class="table100-head">
                    <table>
                        <thead>
                        <tr class="row100 head">
                            <th class="cell100 column1">ID</th>
                            <th class="cell100 column2">Intitulé</th>
                            <th class="cell100 column3">Technologie</th>
                            <th class="cell100 column4">Types</th>
                            <th class="cell100 column5">Etat</th>
                            <th class="cell100 column6">Ouverture</th>
                            <th class="cell100 column7">Fermeture</th>
                        </tr>
                        </thead>
                    </table>
                </div>

                <div class="table100-body js-pscroll">
                    <table class="sortable">
                        <tbody id="list_reports">
                            {% include "ReportYourBug/ApiTemplates/listTemplate.html.twig" %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    {% for report in reportList %}
        <div class="f-modal-container" id="detailsReport{{ report.id }}">
            <div class="f-modal">

                <div class="f-modal__details">
                    <h1 class="f-modal__title">{{ report.title }}</h1>
                    <ul class="f-tagList-type">
                        {% for type in report.types %}
                            <li class="f-tag-type">{{ type.name }}</li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="f-modal__bugInfos">
                    <div class="f-cause">
                        <h2>Cause</h2>
                        <p class="f-modal__text">{{ report.cause }}</p>
                    </div>
                    {% if report.state %}
                        <div class="f-solution">
                            <h2>Solution</h2>
                            <p class="f-modal__text">{{ report.solution }}</p>
                        </div>
                    {% else %}
                        <div class="f-not-solution">
                            <h2>Il n'y a pas encore de solution pour ce bug.</h2>
                        </div>
                    {% endif %}
                </div>
                <button class="f-modal__btn">Fiche &rarr;</button>

                <a href="" class="f-link-2"></a>

            </div>
        </div>
    {% endfor %}

{% endblock %}


{% block script %}
    <script>

        const table = $('#list_reports');
        const tableDefault = table.html();
        const filterTitle = $("#recherche-par-titre");
        const filterID = $("#recherche-par-id");
        const filterTechnology = $('#recherche-par-technology');
        const filterType = $('#recherche-par-type');


        $(document).ready(function(){

            filterTechnology.select2({});
            filterType.select2({});

            $('#recherche-par-titre,#recherche-par-id,#recherche-par-technology,#recherche-par-type').on('keyup change',function (e){

                setTimeout(function(){ },5000)

                if($(this).val() !== "" && (e.keyCode !==16 && e.keyCode !==17 && e.keyCode !==18)){

                    $.ajax({
                        type: 'GET',
                        url:    '{{ path('ryb_api_list') }}',
                        data: {
                            title: filterTitle.val(),
                            id: filterID.val(),
                            technology: filterTechnology.val(),
                            types: filterType.val()
                        },
                        success: function (data){
                            if(data !== ""){

                                table.innerHTML = null;
                                table.html(
                                    data
                                ).fadeIn(10);
                                ps.update()

                            }
                        }
                    });
                }else{
                    table.html(tableDefault);
                }


            });
        });

    </script>
{% endblock %}